ponylang/pony-tutorial

- docs/expressions/exceptions.md
- docs/expressions/methods.md
Noticed this while reading the docs
> Fix a variable declaration

- docs/capabilities/introduction.md
"default defaults" did not make sense to me.
> Possible typo re. default capabilities

- docs/c-ffi/calling-c.md
- docs/c-ffi/linking-c.md
Hi folk,
Initial attempt at an FFI example and some explanatory documentation.
Contributing as I learn! Let me know if you'd like any tweaks or changes.
Cheers,
Darach.
> Add basic C ABI FFI documentation

- docs/c-ffi/calling-c.md
- docs/examples/examples.md
- docs/types/type-aliases.md
I have added some things, I guess some parts need to be removed as they are todo.
> Add some examples

- docs/types/delegates.md
- mkdocs.yml
Add some basic documentation on the use of delegates.
@sylvanc @andymcn Let me know if I got anything wrong and/or need to tweak anything
> Document the basic use of delegates in pony

- docs/types/delegates.md
@andymcn Is it worth adding the final delegate example file to examples in ponyc?
> Fix typo spotted by @andymcn that krept into the docs

- docs/c-ffi/calling-c.md
replace & by addressof
add EGLEvent type decl to the setEvent example.
add some better formatting
> c-ffi/calling-c: updates, fix &

- docs/compiler-clargs/clargs.md
> fix --docs option

- docs/compiler-clargs/clargs.md
> more on --docs

- docs/expressions/methods.md
Minor grammatical fix.
Editor also removed trailing whitespace.
> Minor grammatical fix

- docs/getting-started/installation.md
This patch will also fix the display issues in the "Apt-get and Aptitude" and "Did it work?" sections.
> Use markdown inline code syntax

- types/actors.md
- types/classes.md
- types/primitives.md
Finalisers were missing from the documentation. This fixes the problem.
> Finalisers documentation

- types/primitives.md
> Added McIlvain's explanation of ISize/USize and ILong/ULong

- types/classes.md
> Add section: types/classes.md/Naming rules

- getting-started/installation.md
With the latest from ponyc/README.md
Having this in two places is a bad idea. I really
like the idea of having this in the tutorial but
the existing in 2 places is just awful.
> Bring installation instructions up to date

- capabilities/index.md
Alternate attempt: https://github.com/ponylang/pony-tutorial/pull/123
> Fix Wikipedia/E language link with paren escaping

- expressions/variables.md
- types/classes.md
Inspired by @jemc's explanation on pony+user.
> Add documentation on 'embed' fields

- SUMMARY.md
- appendices/keywords.md
Ivo Balbaert did the vast bulk of this work, I just cleaned up an outstanding PR comment and added an entry for 'embed'.
@ibalbaert - you last pushed to your PR back in April. I hope I'm not treading on your toes by taking it over and giving it a final clean-up.
> Add keywords list based on @ibalbaert's initial PR

- gotchas/divide-by-zero.md
- gotchas/garbage-collection.md
- gotchas/scheduling.md
Hello,
This is a simple revision for typos.
Also, I've added a separate commit for each file. Should they be squashed?
> Revise the new `gotchas` chapter

- SUMMARY.md
- expressions/equality.md
> Add documentation on equality checks

- SUMMARY.md
- generics/generic-constraints.md
- generics/generics-and-reference-capabilities.md
- generics/index.md
This is the start of some documentation for the Generics section of the tutorial. There's a lot more left to do, which I'm still writing but I'd like to push them in smaller pieces so it's not one big review - and I can apply feedback from this to the additional stuff I'm writing.
Please let me know of things to fix up, restructure, add or remove.
> Generics documentation

- README.md
- capabilities/index.md
> add proof link #148

- expressions/control-structures.md
- pattern-matching/as.md
- pattern-matching/case-functions.md
> adding some pony-highlighting where it was missing

- CONTRIBUTING.md
- c-ffi/calling-c.md
So I used a real-ish example because the part just before this seems to. I'm leaving out the extern declaration and 'main', so the code isn't runnable.. Let me know if there's anything I should add/change! 
The only change in `contributing.md` is reogranized -> reorganized
> describe struct usage for C FFI

- expressions/exceptions.md
- expressions/object-literals.md
- expressions/variables.md
Fixed some little things I noticed reading the chapter
> Chapter 3 little Pony fixes, typos etc

- where-next/index.md
It moved as part of new website launch
> Update planet pony location

- gotchas/garbage-collection.md
- gotchas/scheduling.md
- packages/standard-library.md
- testing/ponytest.md
- where-next/index.md
It's moving as part of the move to netlify.
> Update location of online standard library

- pattern-matching/match.md
This PR updates the match ~and case function~ sections to acknowledge exhaustive match.
Part of https://github.com/ponylang/ponyc/issues/1772.
Can be merged when the implemented feature is ready to be merged.
> Update match section to acknowledge exhaustive match.

- types/classes.md
When going through the tutorial myself, I had to switch out and google for the syntax to invoke the named constructor. Thought it would be handy to put this in here in the tutorial.
> Adding constructor invocation sample

- c-ffi/calling-c.md
See https://github.com/ponylang/ponyc/pull/2012.
> Update paragraph on FFI and tuples

- expressions/control-structures.md
> Add examples for loop expression values

- appendices/symbol-lookup-cheatsheet.md
> Add "Chaining" to symbol search keyword table

- SUMMARY.md
- gotchas/side-effect-ordering-in-function-call-expressions.md
> Add side effect ordering in function calls gotcha

- SUMMARY.md
- expressions/methods.md
- gotchas/recursion.md
This section explains the problems associated with recursion, clarifies the cases in which tail-recursion optimisation is applied, and mentions some alternatives to tail-recursion.
> Add recursion to gotchas

- types/traits-and-interfaces.md
describing how to combine multiple traits together, with an accent on the syntax.
> multiple traits

- pattern-matching/index.md
- pattern-matching/match.md
> Add a better explanation of the differences of match by value and match by type

- appendices/compiler-args.md
- appendices/examples.md
> replace options example and mentions with cli

- expressions/literals.md
by making it a fully working code example.
fixes #267
> fix confusing example in literals section

- expressions/methods.md
and fix style guideline violations
fixes #266
> make example for anonymous methods compile

- pattern-matching/match.md
> Typo fixed

- getting-started/what-you-need.md
Added Links to Visual Studio Code Editor with Link to Pony Extension
> Added Visual Studio Code Extension to what-you-need.md

- pattern-matching/match.md
This describes is a technique of a non-obvious way to extract iso references using pattern matching.
> added section on capability inference and match

- appendices/whitespace.md
As per [RFC 50](https://github.com/ponylang/rfcs/blob/master/text/0050-class-actor-fields-docstrings.md).
> Add information on field docstring

- getting-started/how-it-works.md
I think it could make sense to mention a few more of these, especially "reasonably popular" languages in various communities.
> how-it-works: Mention more languages using type postfix

- content/appendices/examples.md
> fix env.vars to public field instead of method

- content/types/actors.md
This came up watching https://www.twitch.tv/videos/378865137 learn Pony.
> Mention that scheduler is cooperative when bringing up for first time

- content/types/at-a-glance.md
The prior link was to the definition of causal which doesn't help you
understand what causal messaging is as a term.
> Provide a definition of causal messaging

- content/getting-started/_index.md
> Update Getting Started Overview to mention rcaps.

- config.toml
This is a requirement for setting up search for the tutorial.
> configure Hugo to create a search-index

- content/types/structs.md
They are a type and should be introduced with others.
Closes #282
> Introduce structs during the types section of tutorial

- content/_index.md
- content/gotchas/garbage-collection.md
- content/where-next/_index.md
We're replacing it with Slack.
> Deprecate IRC

- content/reference-capabilities/aliasing.md
I think fields do not count as variables. Improve legibility
> Small changes

- content/reference-capabilities/_index.md
- content/reference-capabilities/capability-matrix.md
- content/reference-capabilities/guarantees.md
> Add reference capability matrix section

- .github/delete-branch-on-merge.workflow
> Delete branches on merge

- content/c-ffi/calling-c.md
Rename MaybePointer to NullablePointer in tutorial following #3293.
> Rename MaybePointer to NullablePointer

- content/reference-capabilities/consume-and-destructive-read.md
Thanks to Nathan Watts for bringing this up.
> Clear up confusion in destructive read example

- content/expressions/methods.md
- content/types/actors.md
[Brought up on Zulip](https://ponylang.zulipchat.com/#narrow/stream/189985-beginner-help/topic/So.2E.2E.2Ewhere.20is.20the.20tutorial.20for.20Actor.20and.20async.3F).
> Clarify where message passing is explained

- content/types/classes.md
> Interaction between zero-argument constructors and syntactic sugar can be clearer.

- content/_index.md
I added Elixir to the list of languages supporting actors because it's probably the most likely actor model that a Ruby programmer is likely to encounter, and that's a pretty big ecosystem.
> Add Elixir to list of actor model languages

- content/appendices/keywords.md
Added `not` as keyword for logical negation.
> Resolve #413; add not as keyword

- content/getting-started/what-you-need.md
Installation instructions have moved.
> Address change in ponyc/README.md layout

- content/expressions/control-structures.md
- content/packages/package-system.md
https://github.com/ponylang/pony-tutorial/pull/427#pullrequestreview-397352463
Numbered list fixes:
- expressions/control-structures.md
- packages/package-system.md
> Numbered list fixes

- content/reference-capabilities/reference-capabilities.md
Fix numbered list:
- reference-capabilities/reference-capabilities.md
> Fix numbered list

- content/expressions/control-structures.md
I so want to contribute, but have very little to give besides grammar updates. This is my second time taking a stab at learning Pony, and I'm trying to add commas or suggest grammar changes that help clarify the questions that have arisen as I've followed the guides.
> Minor grammar suggestions for clarity

- docs/reference-capabilities/consume-and-destructive-read.md
> Document consume with capability

- docs/appendices/examples.md
- docs/appendices/serialisation.md
- docs/c-ffi/callbacks.md
- docs/c-ffi/calling-c.md
- docs/c-ffi/linking-c.md
Changes related to [RFC 68](https://github.com/ponylang/rfcs/blob/main/text/0068-force-declaration-of-ffi-functions.md)
> Update FFI chapters to reflect RFC 68

- mkdocs.yml
Test to see if settings fix deploy preview in PR
> Add site_url; Exclude htmlproofer errs with dict

- docs/appendices/serialisation.md
- docs/object-capabilities/derived-authority.md
Should only be merged when https://github.com/ponylang/ponyc/pull/3962 is merged,
> Update for Env.root change from RFC 65

- docs/appendices/annotations.md
Shouldn't be merged until the feature PR is:
https://github.com/ponylang/ponyc/pull/3978
> Add nodoc annotation documentation

- docs/appendices/annotations.md
> Add documentation for the nosupertype annotation

- docs/object-capabilities/derived-authority.md
These changes account for the changes in RFC #72.
https://github.com/ponylang/rfcs/blob/main/text/0072-change-stdlib-object-capabilities-pattern.md
> Update derived authority documentation

- docs/expressions/errors.md
> s/in it/it in/

- docs/c-ffi/calling-c.md
This documents the new feature to be introduced in https://github.com/ponylang/ponyc/pull/4060, so this shouldn't be merged until that becomes available in a release.
> Document return-type polymorphism in FFI

- docs/c-ffi/calling-c.md
This documents the new limitation introduced in https://github.com/ponylang/ponyc/pull/4065, so this shouldn't be merged until that becomes available in a release.
> Document FFI call limitations from interfaces

- docs/expressions/object-literals.md
Fixes https://github.com/ponylang/pony-tutorial/issues/558
> Fix line number reference in Lambda example
