ponylang/pony-tutorial

- docs/getting-started/what-you-need-to-start.md
- docs/index.md
- docs/types/static-vs-dynamic.md
It is spelled with a capital "S".
> Correct the capitalization of "JavaScript".

- docs/expressions/exceptions.md
- docs/expressions/infix-ops.md
failure -> fail, manor -> manner, langauge -> language.
> fixes three typos in infix tutorial.

- docs/c-ffi/calling-c.md
- docs/capabilities/arrow-types.md
- docs/capabilities/object-capabilities.md
- docs/expressions/control-structures.md
- docs/expressions/exceptions.md
- docs/expressions/infix-ops.md
- docs/expressions/methods.md
- docs/expressions/sugar.md
- docs/expressions/variables.md
- docs/types/classes.md
- docs/types/traits-and-interfaces.md
Hi Pony creators,
I have worked through the tutorial which is really a nice read, and from what I have seen and understood I like Pony very much, congratulations! Along the way I have collected the typos I saw, most of them are trivial text typos, a few in code sections also: I have corrected them all in this pull request.
I also have a few suggestions which I list here:
1) Section:  Actors - Behaviors
why is amount.min used in this code:
be eat(amount: U64) =>
_hunger_level = _hunger_level - amount.min(_hunger_level)
amount.min has not been introduced yet
Perhaps replace it by:    	_hunger_level = _hunger_level - amount
Which is easier to understand at this level in the tutorial.
2) Section: Control structures - Loops
while count <=  do10 do
env.out.print(count)
count = count + 1
end
<-- …
> correction of some typos

- docs/getting-started/what-you-need-to-start.md
Hi.
I saw that emacs was not present in the list of editors supporting Pony, despite the fact that a [major mode](http://www.vim.org) was already been already published, so I added it.
Also, all the editors had a link to their official websites, but vim. I fixed that.
Cheers!
> Editors update: emacs and vim

- docs/capabilities/recovering-capabilities.md
1. Including the usize() call.
2. Changing trim() to strip(), removing "- 1".
> Tweeked example code to match changes in library

- docs/types/type-aliases.md
The previous example was confusing because
the code had interfaces but the lead in text
said trait. Switched to be very explicit that
it applies to both.
> Clarify complex type example

- docs/types/delegates.md
1 minor typo. 
Editor automatically removes trailing whitespace as well.
> Minor typo

- docs/runtime/garbage-collection.md
- docs/types/static-vs-dynamic.md
Issue https://github.com/ponylang/pony-tutorial/issues/50
* fixed typo in docs/runtime/garbage-collection.md
* emphasized causal in docs/types/static-vs-dynamic.md
* added search links for causal definition in both places
> Emphasize causal for non-native speakers

- docs/expressions/exceptions.md
Based on @sylvanc's explanation here: https://groups.io/g/pony+user/message/106 . I couldn't find them covered in the tutorial; it seemed they belonged best with the rest of exception handling.
> Document 'with' blocks

- .travis.yml
- README.md
@sylvanc you'll need to set up a personal access token that has "repo" access. Then set up a GH_TOKEN env variable for the TravisCI plan for pony-tutorial. Everything else should work after that.
> Have TravisCI build tutorial on push

- docs/expressions/partial-application.md
The examples misse a 'ref' in the function declaration resulting
in it defaulting to 'box'. This causes an error when writing to
the objects field.
The apply method in Bar creates a Foo that defaults to 'iso' and
gives an error about aliasing. Providing a type declaration defaults
it to 'ref'.
> Fix partial application example

- docs/capabilities/reference-capabilities.md
The syntax for types default capabilities changed recently but the tutorial still uses the old version.
> Update default capability syntax

- docs/pattern-matching/as.md
This PR adds content to the tutorial section for `as`.
> Add documentation for `as`

- SUMMARY.md
- docs/c-ffi/callbacks.md
This documentation explains some of the subtle issues around passing
Pony functions to C libraries that will use them as callback
functions. It uses the SQLite `sqlite3_exec` function as an example.
Fixes #83
> Add C FFI callbacks documentation

- SUMMARY.md
- docs/pattern-matching/case-functions.md
This part of the tutorial covers case functions. It discusses:
* how to create a case function
* parameter matching
* guards around functions
* restrictions on parameter naming and parameter types
* return types
There are two examples: a factorial program and a fizzbuzz program.
This fixes issue #77.
> Add case function documentation

- types/primitives.md
Since [ponyc/14b174f](https://github.com/ponylang/ponyc/commit/14b174f89f7cba854ee6638c5638ffa6c27e9a45), a primitive `_init` function takes no parameter.
> Update primitives documentation

- capabilities/reference-capabilities.md
The following sentence at the end of the document was confusing: "So
the default for any mutable reference capability is iso and the
default for any immutable reference capability is val." After some
discussion we decided it didn't make sense and didn't belong in this
part of the documentation, so I've removed it.
> Remove confusing sentence to clarify reference capabilities section

- getting-started/installation.md
Fixes \<code\> bugs in the intro to installing the Pony compiler -- previously text was interspersed with the code snippets, so I switched them to be in-line code instead for better readability. This also adds a link directly to the "Building ponyc from source" section since it is a long way down the page in the current page organization.
> Clean up initial installation explanation

- capabilities/trust-boundary.md
The [sandbox](http://sandbox.ponylang.org/) is not supported at the moment.
> Remove 'Example of use' FFI section

- types/type-expressions.md
This clears up a bit of confusion that a new user encountered:
http://irclog.whitequark.org/ponylang/2016-06-08#1465348929-1465349760;
> Fix description of tuple type expressons to be more accurate.

- capabilities/consume-and-destructive-read.md
This pull requests rewords the intro text in the section describing consume and destructive read to fix a typo ("And" to "An") and to attempt to improve the readability of the sentence.
> Reword introduction text for Consume and Destructive Read section

- expressions/variables.md
Only I would try to put function definitions before field definitions... This is my best reverse engineered guess about Pony's field grammar rules.
> Clarify legal field definitions, minor fixes

- expressions/variables.md
- Specify that embedded fields must be initialised from constructor expressions.
- Modify "Why would I use `embed`?" section. Advise to use `embed` by default and talk about the possible drawbacks for garbage collection.
> Amend embedded fields documentation

- pattern-matching/as.md
Wombats and capybaras are creatures of similar size, build, and furry-ness, but wombats are marsupials, not rodents. While "mammal" is the closest _biological_ category that encompasses both wombats and capybaras, "critter" is more evocative of their roles in popular culture. (Replaces PR #120)
> Replace "Rodent" with "Critter" in example

- expressions/control-structures.md
Pony does not allow printing a UI32 without .string()
> Change print(count) to print(count.string())

- getting-started/hello-world.md
- getting-started/installation.md
Building from source is something that a fair amount of people (myself included) will always shy away from unless absolutely necessary. Docker is the next available option for Pony, but not everyone has used Docker. This request proposes two minor additions to the installation and build instructions. These additions are targeted towards people who are unfamiliar with Docker, and preempt at least two sources of potential mishap and confusion. Namely: 
* You must use absolute paths
* The absolute path must not end with a trailing slash, `/`
> Add clarifications on how to compile using Docker.

- expressions/infix-ops.md
- expressions/methods.md
- pattern-matching/case-functions.md
Several places in the tutorial stated that Pony does not support
overloaded functions. While possibly true for some definition of the
term "overloaded function", this caused some confusion because Pony
does support case functions, which achieve several of the goals of
overloaded functions.
This change adds links to the case function documentation in places
case functions might be helpful, and adds a section to the case
function documentation discussing the ways that case functions might
differ from ones expectations of overloaded functions.
Fixes #106
> Add notes about overloaded functions

- SUMMARY.md
- appendices/error-messages.md
This chapter provides examples of code that fails to compile, the error
messages reported by ponyc, a discussion of the error message and the
code that generated it, and suggestions to correct the code.
It would be good to have a general description of Pony's error messages,
but the three examples I started with do not have much consistency. As
a result, I used three related error messages (on mutable/immutable
problems) and went from simple to complex.
The three errors are:
* left side must be something that can be assigned to
* cannot write to a field in a box function
* receiver type is not a subtype of target type
> Add a chapter describing Pony's error messages to the appendix

- expressions/methods.md
`(Title)[url] -> [Title](url)`
> Fix markdown link syntax in "Methods" section

- c-ffi/calling-c.md
This change reflects the changes about to be made in order to resolve ponylang/ponyc#1240
> Remove ffi tuple example

- expressions/control-structures.md
A `break` with no value now takes its value from the `else` block instead of being an implicit `None`.
> Update break semantics

- appendices/examples.md
- expressions/object-literals.md
This PR updates the tutorial to show the new lambda syntax. It also makes some corrections around some details about lambdas.
See https://github.com/ponylang/ponyc/pull/1400 for the implementation of the change.
> Update tutorial to show new lambda syntax.

- appendices/symbol-lookup-cheatsheet.md
Added an entry for `.>` in symbol-lookup-cheatsheet.md
> Add symbol for method chaining in the cheatsheet

- getting-started/how-it-works.md
This typo was reported via email by eqd4life@gmail.com
> Fix a small typo in "How it works"

- c-ffi/c-abi.md
The existing instructions say to use `clang++` instead of `clang`. This
will result in not being able to link as the c function names will be
managled. Using `clang` fixes the issue.
> Fix linking error in c-abi example

- expressions/infix-ops.md
- expressions/methods.md
- pattern-matching/match.md
I found that some pages of the tutorial had quite odd indentation in some code snippets - it turned out there was a mixture of tabs in there, so this PR converts them to spaces (the only decent indentation mechanism, of course).
> Fix: Convert tabs to spaces in source code.

- appendices/examples.md
- expressions/control-structures.md
- pattern-matching/as.md
- types/type-aliases.md
to the new syntax introduced with pony 12.0 (RFC: https://github.com/ponylang/rfcs/blob/master/text/0037-arrays-as-sequences.md)
which requires semicolon or newline between separate values.
> update array literal examples

- types/actors.md
Since RFC 28 and v0.10.0, all behaviours return None instead of the receiver.
Fixes #196
> Types: behaviours now return None

- appendices/examples.md
- appendices/serialisation.md
- c-ffi/c-abi.md
- c-ffi/calling-c.md
- capabilities/combining-capabilities.md
- capabilities/recovering-capabilities.md
- expressions/control-structures.md
- expressions/exceptions.md
- expressions/methods.md
- expressions/object-literals.md
- gotchas/scheduling.md
- pattern-matching/as.md
- pattern-matching/case-functions.md
- testing/ponytest.md
See https://github.com/ponylang/rfcs/pull/82.
See https://github.com/ponylang/ponyc/pull/2039.
> Update tutorial for explicit partial calls.

- expressions/equality.md
I was experiencing confusion over which side of of `a == b` called `eq`, so I made the section on structural typing easier for me to understand.
> Clarify confusing paragraph about structural equality

- expressions/exceptions.md
A few of the `try`'s and some other keywords/code snippets had no ticks around them, this should (hopefully) catch them all (oh god I used a Pokemon reference -.- I feel so bad, sorry!)
To give context:
@SeanTAllen Licenser: are you saying sometimes it was ` around it and sometimes it doesn't?
@SeanTAllen if yes, then yes, please make keywords always have ` around them where you find they don't
> Update exceptions.md to encapsulate keywords in `

- capabilities/aliasing.md
It came up on IRC and struck me by surprise. Lets avoid this for other users and enable everybody to RTFM them.
> mention that 'this' inside a method body is an alias to the receiver

- SUMMARY.md
- expressions/literals.md
it covers boolean, numeric, character, string and array literals.
Please consider this as a suggestions and feel free to cut, scramble and criticize my writing.
I take no pride from my writing, so roast me. :)
* it might go a little bit too much into detail on array literals and type inference
* it says string literals can contain any unicode characters (which works for me (UTF-8 source file, pony playground) but was reported from several sources that pony does not)
> Add section about literals

- types/classes.md
Correctly and concisely stating what source code elements need to be ASCII may need some tweaking.
> clarify that string literals don't need to be ASCII-only

- book.json
this is a workaround for https://github.com/GitbookIO/plugin-lunr/issues/3 and should fix the issue mentioned on the user list, which was introduces by the literals section containing a caroussel horse emoji. (my bad)
> ignore special characters in search

- pattern-matching/case-functions.md
`String.join` argument was changed. and it cause compilation error.
https://github.com/ponylang/rfcs/blob/master/text/0048-change-String-join-to-take-iterable.md
before
```
Error:
_/main.pony:26:31: argument not a subtype of parameter
env.out.print("\n".join(lines))
^
Info:
_/main.pony:25:62: Array[String val] ref is not a subtype of Iterator[Stringable box] ref: it has no method 'has_next'
let lines = FizzBuzz.fizz_buzz(Range[U64](1, 101))? as Array[String]
^
_/main.pony:25:62: Array[String val] ref is not a subtype of Iterator[Stringable box] ref: it has no method 'next'
let lines = FizzBuzz.fizz_buzz(Range[U64](1, 101))? as Array[String]
```
after
```
Generating
Reachability
Selector painting
Data prototypes
Data types
Function prototypes
Functions
Descriptors
Optimising
Writing …
```
> fix fizzbuzz example for rfc0048

- .gitignore
- book.json
This add a GitBook plugin to add a button to send code samples to the pony playground. There is not much to see in this request because it just add a GitBook plugin that can be seen [here](https://github.com/codec-abc/gitbook-plugin-copy-code-button/blob/master/book/toggle.js). I used [this plugin](https://github.com/WebEngage/gitbook-plugin-copy-code-button) as a base for my own. Basically it works the following way:
It find each code sample in the page and a button near it. When the button is clicked, I retrieve the code in the sample (in a ugly way I think, but I am no Js expert) created a gist of it -using Github API- and finally redirect the page to the playground with the newly created gist.
The drawbacks are the following:
* It change the current page URL (While reader will …
> use gitbook plugin to add button to run code sample

- types/primitives.md
This is an incredibly minor fix for a small formatting issue I notice while going through the tutorial.
`fun multiply(a : U64, b: U64) : U64` should be `fun multiply(a: U64, b: U64) : U64` instead so the formatting is consistent.
> Fix multiply function definition formatting

- types/primitives.md
This fixes the formatting issue mentioned here: https://github.com/ponylang/pony-tutorial/pull/248#issuecomment-343697691
Running `ag "\)\s+:\s*"` across the tutorial only showed these two results with incorrect formatting, so seems like this incorrect whitespace isn't an issue anywhere else.
> Fix formatting for function return types

- expressions/exceptions.md
Pony's error isn't the same as exceptions in other languages. This is
the first pass at addressing.
> Rework "exceptions"

- expressions/control-structures.md
Previously example was invalid. It referenced an out of scope variable.
Closes #218
> Update 'repeat' example to be valid Pony code

- expressions/methods.md
> Remove early reference to "error" in tail call example

- expressions/literals.md
- getting-started/how-it-works.md
The reference in String Literals to a single quote is wrong and changed
triple quote to triple-quoted to be consitent with other uses in the
documentation.
> Cleanup references to quotes

- pattern-matching/match.md
Two examples in match.md do not compile with the either 0.21.3 or the latest versions of ponyc.
The first example, an else, fails because the other matches are exhaustive and therefore else is unreachable.  This else branch is deleted in this patch.
The second example re-uses the variable named y.  This variable is renamed to u in this patch.
> match.md: Fix examples for matches that don't compile.

- expressions/methods.md
Add a comma to break up the sentence and clearly separate the two concepts being references, otherwise it reads like its a single concept.
> Grammar tweak

- expressions/literals.md
String literals are actually single common instance in the entire program, and not different String instances. This can cause some confusion with new programmers (for example, when dealing with identity equality).
Closes #297.
> Add note about string literal instances

- gotchas/divide-by-zero.md
The division by zero section is now more clear about the fact that
integer division by 0 is 0 and floating point division by zero is
`inf` or `-inf`. This well help developers understand what to expect
from division and make it clear that the results will differ depending
on whether the division is of integers or floats.
Closes #310
> Clarify results of integer and floating point division by zero

- gotchas/divide-by-zero.md
The divide by zero section of the tutorial used the word "insane" to
describe the fact that in Pony 1/0=0. Mental health advocates have
pointed out that words like "insane" and "crazy" stigmatize the
mentally ill. This change helps to foster an inclusive and welcoming
community.
Fixes #308
> Remove use of the word "insane" in divide-by-zero section

- gotchas/divide-by-zero.md
The code sample in the section on dividing by zero was not valid Pony
code. It has been fixed and is now valid. This will make it easier for
people who are learning about the language to experiment with the
example.
Fixes #309
> Fix divide-by-zero code sample

- capabilities/combining-capabilities.md
This addresses a lack of explanation for when it is safe to write to the fields of objects. Though this relationship can be inferred based on the viewpoint adaptation table, it definitely requires some introduction for newcomers to the language.
> Add explanation of safe-to-write relation between capabilities

- capabilities/recovering-capabilities.md
The first example is ambiguous because it uses a type name to invoke the default constructor, so it is unclear to the reader whether an expression or a type follows the recover keyword.
> Clarify that recover wraps a list of expressions

- capabilities/consume-and-destructive-read.md
Method must be ref because it changes  fields
> Method must be ref because it changes  fields

- capabilities/recovering-capabilities.md
This clarification was suggested by @shelby3 [here](https://github.com/ponylang/pony-tutorial/issues/321#issuecomment-444375298).
Resolves #321.
> Update section on auto-recovery to clarify that receiver need not be sendable.

- content/gotchas/divide-by-zero.md
Didn't get converted over when we moved from Gitbook to Hugo.
Closes #342
> Fix broken links in divide-by-zero gotchas

- content/types/type-aliases.md
It's not needed to understand the example and could be confusing.
> Remove unneeded reference capability in example

- content/expressions/variables.md
This PR cleans up some messy/distracting text in the Variables page in favor of some more concise, clear language. It also better separates the section of the page talking about embedded fields.
> Some clarifications in the Variables page.

- content/appendices/keywords.md
After looking through the stdlib code and trying to piece together what the LLVM code that implements `digestof` does, I've created an addition to `keywords.md` for a missing keyword, `digestof`.  I'm not sure that I'm correct, and I'm pretty sure that it's ugly.  Alternative definitions are welcome.
> Add strawman definition of  `digestof` to keywords.md

- content/_index.md
- content/where-next/_index.md
The mailing lists get very little usage and are being dropped.
> Remove references to groups.io

- content/reference-capabilities/capability-subtyping.md
- content/reference-capabilities/combining-capabilities.md
- content/reference-capabilities/passing-and-sharing.md
The "Combining Capabilities" section of the tutorial covers topics that are more advanced than the previous ones. Placing it after "Capability Subtyping" means that someone reading the tutorial could start writing toy programs that send simple messages to other actors, such as `String iso`, right after reading "Passing and Sharing References".
> Reorder "Reference Capabilities" sections

- content/types/structs.md
Hello! I was going through the tutorial and noticed this typo, so here is a PR fixing it. Thanks!
> Fix typo in structs section: s/throughtout/throughout

- content/expressions/arithmetic.md
Found this while reading the documentation, I think that the focus was on how to intentionally get an overflow. With the provided example I was getting a compilation error:
```
argument not a subtype of parameter
I32.max_value() +? env.args.size()
```
```
argument type is USize val
I32.max_value() +? env.args.size()
```
```
parameter type is I32 val
fun add_partial(y: I32): I32 ? =>
^
```
```
USize val is not a subtype of I32 val
fun size(): USize =>
^
```
> change type from I32 to USize in example to make it compile

- content/expressions/methods.md
- content/expressions/object-literals.md
Based on the documentation, String.hash() is USize, not U64:
https://stdlib.ponylang.io/builtin-String/#hash
> fix hashable object literal, String.hash() is USize, hash64() should be used

- content/object-capabilities/object-capabilities.md
Neither myself nor Epic Eric are able to understand exactly what the
removed section means. It came up in beginner help. We think it is
confusing for a beginner, not really on topic and should be removed.
> Remove referential transparency mention

- content/appendices/memory-allocation.md
- content/c-ffi/c-abi.md
- content/expressions/literals.md
As Pony is the name of the language, any plaintext/non-code mentions of it should have the name capitalized.
Note that the String Literals that mention `pony` as a variable name have not been changed as these were the only code mentions of pony
> Capitalize non-code mentions of Pony

- content/testing/_index.md
"Testing" was the only major section without "Overview" as its first subsection/_index title.
> Make Overview the first subsection of Testing

- content/appendices/error-messages.md
- content/gotchas/side-effect-ordering-in-function-call-expressions.md
Later in the tutorial some subsection headers are not titlecased. Note: There are also internal sections for individual entries that break this rule (see https://tutorial.ponylang.io/appendices/error-messages.html where the internal section have no capitals), but I only fixed the headers in the navigation. If we wish to apply this rule generally across all sections no matter there level I can certainly do this. There is also a configuration option to this effect for Hugo, see https://gohugo.io/getting-started/configuration/#configure-title-case but I am unsure where all the Hugo title macro is used currently.
> Titlecasing for all subsections

- content/reference-capabilities/reference-capabilities.md
In "Reference Capabilities" > "Reference Capabilities" > "Type qualifiers".
> Clarify that refcaps are specific to instances

- content/reference-capabilities/reference-capabilities.md
Added a simple example and reworded "`class Foo`" as "class `Foo`", where
applicable, to make it clear that we are not using a type definition yet.
Closes #404.
> Clarify default refcaps on classes/objects

- content/expressions/literals.md
The previous example has an explicit Array type annotation and the
example containing the "as" expression does not need that since it wants
to demonstrate how the coercion can be achieved by expressing the type
of the elements in the Array after with "as".
> Improve example that illustrates what "as" expressions are for

- content/appendices/keywords.md
Added third use of `is` keyword for identity comparison and `isnt` entry as negative identity comparison in keyword table.
> Resolve #336; is/isnt keywords use for identity comparison

- content/expressions/methods.md
Try to clarify use of `where` by restating that it is needed in order to use named arguments, and provide side-by-side positional/named examples to draw attention to the use of `x` and `y` out of user in named argument example.
> Fix #291; Add emphasis on use of where for named arguments

- content/appendices/ponypath.md
Fixed #95 by adding a brief statement about the purpose of `PONYPATH` and instructions on how to add an example directory to `PONYPATH` on Unix and Windows.
> Add PONYPATH to Appendices

- content/expressions/methods.md
Fixes #284 by adding the `var a: T => a.create()` syntax after introduction of constructors.
> Add self-referential constructor call

- content/expressions/ops.md
Fixes #324 by adding an example of mixed unary and infix/binary operators in a single expression.
I opted to retain the term "infix" as used in the Precedence subsection right now rather than introduce the term "binary" into the mix and need to explain "binary" is "infix" here. 
As well (because I anticipate the future question on this point), I added a brief example of using a unary operator on parentheses around an infix operator's expression.
Lastly, I made a comment after each mathematical expression in the Precedence subsection with its mathematical result, including "Compilation failed." for those that do not compile as is.
> Add clarifying examples of unary versus binary operator precedence

- content/appendices/keywords.md
Adds the missing `compile_intrinsic` keyword to Appendices/Keywords table.
Closes #422
> Add compile_intrinsic keyword

- content/types/classes.md
This paragraph talking about numbers lead me to a few minutes wondering why this rule about prime numbers exists, before I realized you meant prime-the-single-quote.
> Split talk about 's and numbers to avoid prime confusion

- content/expressions/object-literals.md
A sentence in the paragraph that explains when a lambda requires `ref` reads awkwardly. The biggest problem is that it appears to be missing a comma:
> In a lambda that **captures references, this needs** to be `ref` if the function needs to modify any of the captured variables or call `ref` methods on them.
> Clarifying when a lambda requires a `ref` reference capability

- content/expressions/partial-application.md
Reworked the "Partial application is just an object literal" section.
It's hard not to combine multiple changes here, but this was an opportunity to make the admittedly bold change that we should use `lambda` here as it's likely far more familiar than `object literal`, and it reads better in the title imo.
Besides that, just re-order before the section that references it, change 'captures' to 'captures aliases of', and add an explaining sentence why we can't consume unique references, fixing #439
> Rework the partial application object literal section (fixes https://github.com/ponylang/pony-tutorial/issues/439)

- content/reference-capabilities/combining-capabilities.md
This is a reworking of the `trn` origin section of viewpoint adaptation to explain why `trn->trn` should be `box` for the issue mentioned at https://github.com/ponylang/ponyc/issues/3572
> Update viewpoint table and explanation for `trn->trn` = `box`

- content/reference-capabilities/combining-capabilities.md
Explanation below:
While it is true that access to receivers and fields will follow
this, in that `this` is just a normal variable, I feel this outlook
could be confusing when understood with receiver recovery, and
changing of capabilities.
A reader might conclude or speculate that a variable with type iso,
can only see its own contents with those viewpoints, but the notion
of an object accessing itself is most closely aligned with calling
a function (or behavior). Since this will almost certainly be
`fun ref` and `fun box`, the reader may become confused by
reading it as though it would apply to those functions on `iso`
variables.
I'm not implying that it would be sensible to conclude that, but
that a reader may get confused that that would seem to be implied.
> Combining capabilities: Rework the "see its own fields" wording of viewpoint adaptation.

- content/expressions/control-structures.md
Issue #440 was discussed in today's sync call. I mentioned there that I think it's least confusing to just avoid saying "these are not statements" while still saying positively that "these are all expressions".
Resolves #440.
> Clear up confusion about statements as expressions

- content/reference-capabilities/combining-capabilities.md
This is a simultaneous issue I had when starting and a proposed fix with the knowledge I have now.
When first reading this, the section on viewpoints and fields was rather confusing, since it didn't feel clear what it *meant* to have a capability of a field (and we never actually mentioned them in the classes chapter). This introduces them, and makes sure to specify that a field makes the same exact global guarantees.
> Describe capabilities of fields before discussing viewpoint adaptation

- content/appendices/serialisation.md
Without a blank line, the bullet points are rendered verbatim and in a single paragraph, making it hard to read.
Link: https://tutorial.ponylang.io/appendices/serialisation.html
> Fix whitespace

- content/appendices/annotations.md
- content/expressions/arithmetic.md
- content/gotchas/divide-by-zero.md
- content/reference-capabilities/capability-matrix.md
1. `content/appendices/annotations.md` (line 59): a a `struct` -> a `struct`
2. `content/expressions/arithmetic.md` (line 169): typle -> tuple
3. `content/gotchas/divide-by-zero.md` (line 36): dependend -> dependent
4. `content/reference-capabilities/capability-matrix.md` (line 46): somewehre -> somewhere
> Fix some typos

- mkdocs.yml
Re-enabling this locally produced the following error so I am looking to see if there are any issues with building on Netlify.
```error
ERROR   -  Error building page 'expressions/variables.md': https://github.com/ponylang/pony-tutorial/: 429
```
> Re-enable htmlproofer

- docs/object-capabilities/trust-boundary.md
The net/ssl package was extracted into its own independent library.
> Remove net/ssl package from safe example

- docs/appendices/examples.md
- docs/c-ffi/calling-c.md
This is a general stab at making the FFI docs better / clarifying some details. Hopefully the commit messages clarify individual changes.
Fixes #263, #303 and #466.
Resolves some of the points raised in #82, but maybe it should be kept open as a "catch-all" FFI docs improvement issue.
And I think #332 is also fixed by this, by clarifying that structs are equivalent to pointer to structs from the C point of view.
> Improve FFI documentation

- docs/types/at-a-glance.md
Even though it is true that we can't make guarantees around FFI calls, the pony type system coupled with the now mandatory "use" statements does provide all the tools a programmer needs to guarantee that the data that they pass into their FFI functions is correct.
(Where "correct" is left as an exercise to the reader as they are the ones that need to strictly define what is "correct".  We can't automatically validate either the "shape" of the data or derive who manages the memory).
The point being, if they correctly describe the data using pony types, the pony compiler *will* enforce the shape of that data for them consistently throughout their application.  That is *huge*.
(How to map pony-types and build type-systems that are flexible _and_ safe is 95% of the difficulty of doing C-FFI)
> The mandatory FFI "use" change improves our safety story.

- docs/appendices/keywords.md
This is not used anymore now that the `{(a: Foo): Bar => ...}` syntax is used.
> Remove lambda from keywords

- docs/.lide_workspace.lua
- docs/reference-capabilities/combining-capabilities.md
- docs/reference-capabilities/reference-capabilities.md
I found some words like "val" and "tag" without back-ticks and one specific line where "if" was written instead of "it"
> Fixed words not highlighted/embed and one typo in chapter "reference-capabilities"

- docs/pattern-matching/as.md
The new version is a nice improvement! Just found out a couple of typos when reading it out loud.
> Fix typos in `as` documentation

- docs/types/traits-and-interfaces.md
This commit provides a rewrite of the traits and interfaces documentation.
The goals are:
- Be more nuanced in the differences between trait and interface
In particular, acknowledge that interfaces can be used for both
structural and nominal subtyping.
- Explain the differences between trait and interface
The previous content was focused almost entirely on nominal vs
structural subtyping and didn't give folks who aren't experienced
with both examples to demonstrate the advantages of each approach
as well as the different affordances they provide.
> Elaborate on trait vs interface differences

- docs/expressions/errors.md
There's no longer an `else` clause, it is purely `with`.
See https://github.com/ponylang/ponyc/pull/4024
> Update `with` documentation to match new implementation

- docs/appendices/examples.md
- docs/testing/ponytest.md
It was changed to `pony_test` to conform with naming conventions.
> Updates for PonyTest package rename

- docs/types/traits-and-interfaces.md
This PR adds the missing `USize` return type to the `Compactable` interface's `size()` method. Without it, the example fails with a compile error:
```
❯ ponyc
Building builtin -> /home/djavorszky/.local/share/ponyup/ponyc-release-0.49.0-x86_64-linux-gnu/packages/builtin
Building . -> /home/djavorszky/dev/helloworld
Error:
/home/djavorszky/dev/helloworld/main.pony:74:21: couldn't find 'gt' in 'None'
if thing.size() > _threshold then
```
> Add missing return type to Compactable#size()

- docs/reference-capabilities/reference-capabilities.md
Looks like this was once “we’ll cover that” and was supposed to be switched to “that we’ll cover”, but… well, that’s that.
> Remove extraneous ‘that’

- docs/generics/generic-constraints.md
Having `fun ref get(): this->A => _c` results in compile error:
> Error:
/home/djavorszky/dev/helloworld/main.pony:7:18: can only use 'this' for a viewpoint in a box function
fun ref get(): this->A => _c
Works with `fun get(): this->A => _c`
> Generic 'get' function should have default refcap

- docs/c-ffi/c-abi.md
The Pony version was implementing a buggy version of
https://arxiv.org/abs/1406.2294, while the C version was implementing a
different version, albeit incompatible, from the same paper.
---
Fixes #181
> Fix Pony and C code for jump consistent hash

- docs/appendices/examples.md
- docs/expressions/control-structures.md
- docs/gotchas/garbage-collection.md
- docs/pattern-matching/match.md
* appendices/examples.md - UnitTest.apply() returns None, not TestResult.
expect_eq method is now assert_eq
* expressions/control-structures.md - typo in the variable name.
* gotchas/garbage_collection.md - Missing => in constructor line,
missing use "collections" needed for Range.
* pattern-matching/match.md - Mandatory constructor for Main added.
> Brought examples up to date with current Pony syntax and package requirements.

- .github/linters/.markdown-lint.yml
The default value is 2, but mkdocs needs at least 4 spaces in order to correctly
render nested lists. See https://github.com/mkdocs/mkdocs/issues/545 for more
details.
> Set lint for unordered list indentation to 4 spaces

- .gitattributes
Right now GitHub does not detect the language of this repo:
After the fix it will identify Markdown as the main language:
In my opinion, this will help people (e.g. documentation writers and beginner programmers) to find a project to contribute to.
> Advertise Markdown files in docs/ as "source" files

- .github/workflows/verify-site-builds.yml
Currently, a person opening a PR can be surprised by failures unrelated
to their changes. In particular, to URLs that are external to the site
no longer working and failing validation.
Worse, this means that users of the tutorial are experiencing broken
URLs that won't be discovered until someone does an update for the
tutorial and the build fails.
This commit adds a nightly job that tries to build the site and if it
fails, alerts to Zulip so we can be made aware of issues in a timely
fashion and can endeavor to fix them as soon as possible.
The workflow can also be triggered manually if need be.
> Build the tutorial nightly to get alerts if it fails

- docs/c-ffi/calling-c.md
It wasn't clear that a struct as a return value from C should be read as "pointer to struct".
> Clarify that `struct` is always a pointer

- docs/index.md
> Clarify a couple points in the intro

- docs/expressions/errors.md
Emphasize that all disposable objects listed in the first line of `with` block can be used within the block.
> Improve example of `with` block with multiple objects

- mkdocs.yml
… to make the color mode switcher more perceptible
As discussed in https://github.com/ponylang/ponylang-website/pull/979#issuecomment-2021203578
> Use same (combined) icon for both color schemes

- docs/expressions/sugar.md
> There's more sugar

- docs/expressions/variables.md
> Fix typo in scope example
